config/routes.rb
Rails.application.routes.draw do
  resources :log_hours

  resources :profiles

  match "/tasks/:id/complete", to: "tasks#complete", via: [:get, :post]
  resources :tasks do
  	member do
  		post :complete
  	end
  end

  devise_for :users
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/log-hours', to: 'hours#log_hours', via: 'get'
  match '/admin', to: 'static_pages#admin', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	has_many :collaborators
	validates :hours_to_complete, numericality: true, allow_nil: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]
  before_action :authenticate_user!
  before_action :validate_user, only: [:show]

  # GET /tasks
  # GET /tasks.json
  def index
    @unopened_tasks = Task.where(user_id: current_user.id, complete: :false, open_task: false)
    @open_tasks = current_user.tasks.where(open_task: true, complete: false)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasks = Task.all
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @users = User.all
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.assigned_by = current_user.username
    respond_to do |format|
      if @task.save
        UserMailer.task_email(@task).deliver
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js 
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update    
    respond_to do |format|
      if @task.update(task_params)
        if @task.hours_to_complete == nil
          format.html { redirect_to @task, notice: 'Task was successfully updated.' }
          format.json { render :show, status: :ok, location: @task }
          format.js {render inline: "location.reload();"}
        else
          format.html { redirect_to root_path, notice: 'Task was successfully closed.' }
          @task.update(complete: true)
        end
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy

    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render layout: false}
    end
  end

  #custom method allows user to put in hours and close the task
  def complete
    @task = Task.find(params[:id])
    @task.complete=true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    #ensure user can only view their specific tasks
    def validate_user
      if current_user.id == Task.find(params[:id]).user_id
        #valid user, display the page! 
      else
        flash[:error] = "You must login to continue"
        redirect_to(root_path)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :hours, :due_date, :user_id, :open, :assigned_by,
        :hours_to_complete, :open_task, :complete)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
  <%= simple_form_for(@task, :remote => true ) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :description, as: :text %>
      <%= f.input :hours, label: "Estimated Time (hours)" %>
      <%= f.input :due_date %>
      <%= f.input :user_id, :label => "Assign To" do %>
        <%= f.select :user_id, User.all.map { |u| [u.username, u.id] }, include_blank: true %>
        <% end %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, class: "submit-margin" %>
    </div>
  <% end %>

app/views/tasks/_task.html.erb
<% if task.open_task? %>
  <tr>
    <td> <%= task.id %> </td>
    <td> <%= task.title %></td>
    <td> <%= task.assigned_by %></td>
    <td> <%= task.due_date.strftime("%d %b %y") %> </td>
    <td><%= link_to 'Show', task, class: "btn btn-sm btn-primary" %></td>
    <td> <%= link_to 'Complete', complete_task_path(task), class: "btn btn-sm btn-success" %>
    </td>
    <td> <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-sm btn-primary' %></td>
    <td> <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, remote: true,class: 'btn btn-sm btn-danger delete-task' %></td>
  </tr>
<% else %>
   <tr id = "tr_<%= task.id %>">
      <td> <%= task.id %> </td>
      <td> <%= task.title %></td>
      <td> <%= task.assigned_by %></td>
      <td> <%= task.due_date.strftime("%d %b %y") %> </td>
      <td> <%= link_to "Open", task_path(task, task: { open_task: true }), method: :put, remote: true,
      class: "btn btn-sm btn-primary" %>
      </td>
      <td> <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "btn btn-sm btn-danger delete-task" %>
      </td>
  </tr>
<% end %>

app/views/tasks/complete.html.erb
<div class="row">
	<div class= "col-md-12">
		<h1> Task: <%= @task.title %> </h1>
		<br>

		<%= simple_form_for(@task) do |f| %>
		    <%= f.error_notification %>
		    <div class = "col-md-4"> <%= f.input :hours_to_complete %> </div>
		    <div class= "col-md-2 complete"><%= f.button :submit, "Complete task", class: 'btn btn-success' %></div>
		<% end %>
	</div>
</div>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#unopened-tasks table tr:last').after(' <%= j render(@task) %> </td></tr>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('.delete-task').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});

app/views/tasks/edit.html.erb
<h1>Complete The Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class = "row">
	<div class= "col-md-12">
		<%= link_to "New Task", new_task_path, id: "new_link", remote: true, class: "btn btn-small btn-success" %>
	</div>
  <div id="open-tasks" class = "col-md-7">
  	<h2> Current Tasks </h2>
  	<table class="table" id="open-table">
  		<thead>
		    <tr>
		      <th> # </th>
		      <th> Title </th>
		      <th> Assigned By </th>
		      <th> Due Date </th>
		      <th> View </th>
		      <th> Complete </th>
		      <th> Edit </th>
		      <th> Destroy <th>
		    </tr>
		</thead>
		<tbody>
   			<%= render @open_tasks %>
   		</tbody>
   	</table>
  </div>
  <div id="unopened-tasks" class = "col-md-5">
  	<h2> Upcoming Tasks </h2>
  	<table class="table">
  		<thead>
		    <tr>
		      <th> # </th>
		      <th> Title </th>
		      <th> Assigned By </th>
		      <th> Due Date </th>
		      <th> View </th>
		      <th> Complete </th>
		    </tr>
		</thead>
		<tbody>
   			<%= render @unopened_tasks %>
	   </tbody>
	</table>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @task.hours %>
</p>

<p>
  <strong>Tentative due date:</strong>
  <%= @task.due_date %>
</p>

<p>
	<strong> Assigned by: </strong>
	<%= @task.assigned_by %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
<% if @task.open_task? %>
  $('#edit_task_<%= @task.id %>').appendTo('#open-tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#unopened-tasks');
<% end %>