config/routes.rb
Rails.application.routes.draw do
  resources :log_hours

  resources :profiles

  match "/tasks/:id/complete", to: "tasks#complete", via: [:get, :post]
  resources :tasks do
  	member do
  		post :complete
  	end
  end

  devise_for :users
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/log-hours', to: 'hours#log_hours', via: 'get'
  match '/admin', to: 'static_pages#admin', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand nav-background" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse nav-custom" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Tasks", tasks_path %></li>
        <li><%= link_to "About", about_path, remote:true %></li>
        <li><a href="#">Find a Person</a></li>
      </ul>
      
      <ul class="nav navbar-nav nav-right">
        <% if user_signed_in? %>     
              <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
              <li> <%= link_to "Log Hours", new_log_hour_path %> </li>
              <% if admin %>
                <li> <%= link_to "Admin Panel", admin_path %> </li>
              <% else %> 
                <!-- show nothing, it's a secret... -->  
              <% end %>
            </ul>
        <% else %>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
          <li> <%= link_to "Login", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoreSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/nav" %>
	<div class="container">
		<p class="notice"><%= notice %></p>
		 <p class="alert"><%= alert %></p>
		<%= yield %>
	</div>
</body>
</html>