config/routes.rb
Rails.application.routes.draw do
  resources :log_hours

  resources :profiles

  match "/tasks/:id/complete", to: "tasks#complete", via: [:get, :post]
  resources :tasks do
  	member do
  		post :complete
  	end
  end

  devise_for :users
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/log-hours', to: 'hours#log_hours', via: 'get'
  match '/admin', to: 'static_pages#admin', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
end

app/models/log_hour.rb
class LogHour < ActiveRecord::Base
  belongs_to :user

  validates :hours, numericality: true, allow_nil: false
end

app/controllers/log_hours_controller.rb
class LogHoursController < ApplicationController
  before_action :set_log_hour, only: [:show, :edit, :update, :destroy]

  # GET /log_hours
  # GET /log_hours.json
  def index
    @log_hours = LogHour.all
  end

  # GET /log_hours/1
  # GET /log_hours/1.json
  def show
  end

  # GET /log_hours/new
  def new
    @log_hour = LogHour.new
  end

  # GET /log_hours/1/edit
  def edit
  end

  # POST /log_hours
  # POST /log_hours.json
  def create
    @log_hour = LogHour.new(log_hour_params)

    respond_to do |format|
      if @log_hour.save
        format.html { redirect_to root_path, notice: 'Successfully logged your hours.' }
        format.json { render :show, status: :created, location: @log_hour }
      else
        format.html { render :new }
        format.json { render json: @log_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /log_hours/1
  # PATCH/PUT /log_hours/1.json
  def update
    respond_to do |format|
      if @log_hour.update(log_hour_params)
        format.html { redirect_to @log_hour, notice: 'Log hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @log_hour }
      else
        format.html { render :edit }
        format.json { render json: @log_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_hours/1
  # DELETE /log_hours/1.json
  def destroy
    @log_hour.destroy
    respond_to do |format|
      format.html { redirect_to log_hours_url, notice: 'Log hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_hour
      @log_hour = LogHour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_hour_params
      params.require(:log_hour).permit(:hours).merge(user_id: current_user.id)
    end
end

app/helpers/log_hours_helper.rb
module LogHoursHelper
end

app/views/log_hours/_form.html.erb
<%= simple_form_for(@log_hour) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-4">
    <%= f.input :hours %>
  </div>

  <div class="col-md-2 complete">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/log_hours/edit.html.erb
<h1>Editing log_hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @log_hour %> |
<%= link_to 'Back', log_hours_path %>

app/views/log_hours/index.html.erb
<h1>Listing Hours</h1>

<table>
  <thead>
    <tr>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @log_hours.each do |log_hour| %>
      <tr>
        <td><%= log_hour.hours %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log hour', new_log_hour_path %>

app/views/log_hours/new.html.erb
<div class = "row pad-bottom" ><h1>Log your hours</h1></div>
<div class= "row">
	<div class= "col-md-12">
		<%= render 'form' %>
	</div>
</div>

app/views/log_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hours:</strong>
  <%= @log_hour.hours %>
</p>

<p>
  <strong>User:</strong>
  <%= @log_hour.user %>
</p>

<%= link_to 'Edit', edit_log_hour_path(@log_hour) %> |
<%= link_to 'Back', log_hours_path %>